version: "3.2"

secrets:
   pgsql_db_user:
      external: true
   pgsql_db_pwd:
      external: true
   kc_user:
      external: true
   kc_pwd:
      external: true

volumes:
   postgres_data:
      driver: local

services:
   postgres:
      image: postgres:14.3
      volumes:
         - postgres_data:/var/lib/postgresql/data
      secrets:
         - pgsql_db_user
         - pgsql_db_pwd
      environment:
         POSTGRES_DB: keycloak # database name NON iniettabile attraverso secret nel container keycloak
         POSTGRES_USER_FILE: /run/secrets/pgsql_db_user
         POSTGRES_PASSWORD_FILE: /run/secrets/pgsql_db_pwd
      ports:
         - target: 5432
           published: 5432
           mode: host

   keycloak:
      image: quay.io/keycloak/keycloak:22.0
      secrets:
         - pgsql_db_user
         - pgsql_db_pwd
         - kc_user
         - kc_pwd
      environment:
         KC_DB: postgres
         KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
         KC_DB_USERNAME: Admin
         KC_DB_PASSWORD: tirocinio0799000!
         KEYCLOAK_ADMIN: Admin
         KEYCLOAK_ADMIN_PASSWORD: tirocinio0799000
         KC_HOSTNAME_STRICT: "false"
         KC_HTTP_ENABLED: "true"
      command: start-dev
      volumes:
         - ./cert:/etc/x509/https
      ports:
         - target: 8080
           published: 8443
           mode: host
      depends_on:
         - postgres
