docker_registry_password: "{{ lookup('ansible.builtin.password', 'credentials/container-registry-password', length=32) }}"
postgres_password: "{{ lookup('ansible.builtin.password', 'credentials/postgres-password', length=32) }}"

# Main postgres credentials
DB_USR: postgres
DB_PWD: "{{ lookup('ansible.builtin.password', 'credentials/postgres-password', length=32) }}"

# Dex database credentials (todo 14a)
DEX_USR: dex_user
DEX_PWD: "{{ lookup('ansible.builtin.password', 'credentials/dex-db-password', length=32) }}"
DEX_DB: dex_db

# Forgejo database credentials (todo 14b)
FOR_USR: forgejo_user
FOR_PWD: "{{ lookup('ansible.builtin.password', 'credentials/forgejo-db-password', length=32) }}"
FOR_DB: forgejo_db
FOR_SCR: "{{ lookup('ansible.builtin.password', 'credentials/forgejo-secret', length=64) }}"
FOR_EMAIL: admin@vcc.internal

# Forgejo configuration secrets (todo 31)
FOR_JWT_SCR: "{{ lookup('ansible.builtin.password', 'credentials/forgejo-jwt-secret', length=64) }}"
FOR_SCR_KEY: "{{ lookup('ansible.builtin.password', 'credentials/forgejo-secret-key', length=64) }}"
FOR_CK_USR: vcc_git_username
FOR_RMB_NM: vcc_git_remember_me
FOR_INT_TOK: "{{ lookup('ansible.builtin.password', 'credentials/forgejo-internal-token', length=64) }}"

# Grafana database credentials (todo 14c)
GR_USR: grafana_user
GR_PWD: "{{ lookup('ansible.builtin.password', 'credentials/grafana-db-password', length=32) }}"
GR_DB: grafana_db
GR_SCR: "{{ lookup('ansible.builtin.password', 'credentials/grafana-secret', length=64) }}"
GR_AD_USR: admin
GR_AD_PWD: "{{ lookup('ansible.builtin.password', 'credentials/grafana-admin-password', length=32) }}"

# Dex admin credentials (todo 26)
DEX_ADMIN_EMAIL: admin@vcc.internal
DEX_ADMIN_USER: admin
DEX_ADMIN_ID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
DEX_ADMIN_PWD: "{{ lookup('ansible.builtin.password', 'credentials/dex-admin-password', length=32) }}"

