package TestCases;

import org.junit.BeforeClass;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
import TestCases.PO.MantisBT.*;

public class MantisTestCases {

    @BeforeClass()
    public static void setup() {
        // System.setProperty("webdriver.gecko.driver", "InsertGeckoPathHere");
    }

    private WebDriver driver;

    private Map<String, Object> vars;

    private JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void test1AddUser() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToManage();
        ManagePO _ManagePO = new ManagePO(driver, js, vars);
        _ManagePO.goToManageUsers();
        ManageUsersPO _ManageUsersPO = new ManageUsersPO(driver, js, vars);
        _ManageUsersPO.goToCreateUser();
        CreateAccountPO _CreateAccountPO = new CreateAccountPO(driver, js, vars);
        _CreateAccountPO.createAccount("username001", "username001", "username@username.it", "updater");
        EditUserPO _EditUserPO = new EditUserPO(driver, js, vars);
        _EditUserPO.goToManageUser(true, true, false);
        assertThat(_EditUserPO.set_CSSSELECTOR_row_1tdnth_child1_1(), is("username001"));
        assertThat(_EditUserPO.set_CSSSELECTOR_row_1tdnth_child2(), is("username001"));
        assertThat(_EditUserPO.set_CSSSELECTOR_row_1tdnth_child3(), is("username@username.it"));
        assertThat(_EditUserPO.set_CSSSELECTOR_row_1tdnth_child4(), is("updater"));
        _ManageUsersPO.doLogout();
    }

    @Test
    public void test2AddAlreadyExistingUser() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToManage();
        ManagePO _ManagePO = new ManagePO(driver, js, vars);
        _ManagePO.goToManageUsers();
        ManageUsersPO _ManageUsersPO = new ManageUsersPO(driver, js, vars);
        _ManageUsersPO.goToCreateUser();
        CreateAccountPO _CreateAccountPO = new CreateAccountPO(driver, js, vars);
        _CreateAccountPO.createAccount("username001", "username001", "username@username.it", "updater");
        EditUserPO _EditUserPO = new EditUserPO(driver, js, vars);
        assertThat(_EditUserPO.goToManageUser_1(), is("That username is already being used. Please go back and select another one."));
        WebElement element = driver.findElement(By.xpath("//p"));
        String attribute = element.getAttribute("style");
        vars.put("_style", attribute);
        assertEquals(vars.get("_style").toString(), "color: red;");
        _ManageUsersPO.doLogout();
    }

    @Test
    public void test3AddEmptyUser() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToManage();
        ManagePO _ManagePO = new ManagePO(driver, js, vars);
        _ManagePO.goToManageUsers();
        ManageUsersPO _ManageUsersPO = new ManageUsersPO(driver, js, vars);
        _ManageUsersPO.goToCreateUser();
        CreateAccountPO _CreateAccountPO = new CreateAccountPO(driver, js, vars);
        _CreateAccountPO.click_CSSSELECTOR_button();
        EditUserPO _EditUserPO = new EditUserPO(driver, js, vars);
        _EditUserPO.goToManageUser(false, false, true);
        String expected = "A necessary field \"\" was empty. Please recheck your inputs.";
        assertThat(_EditUserPO.set_CSSSELECTOR_trnth_child2center_1(), is(expected));
        
        WebElement element = driver.findElement(By.xpath("//p"));
        String attribute = element.getAttribute("style");
        vars.put("_style", attribute);
        
        assertEquals(vars.get("_style").toString(), "color: red;");
        _ManageUsersPO.doLogout();
    }

    @Test
    public void test4AddProject() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_NAME_username("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToManage();
        ManagePO _ManagePO = new ManagePO(driver, js, vars);
        _ManagePO.goToManageProjects();
        ManageProjectsPO _ManageProjectsPO = new ManageProjectsPO(driver, js, vars);
        _ManageProjectsPO.goToCreateProject();
        CreateProjectPO _CreateProjectPO = new CreateProjectPO(driver, js, vars);
        _CreateProjectPO.createProject("Project001", "release", "Description");
        _ManageProjectsPO.goToManage();
        _ManagePO.goToManageProjects_1();
        assertThat(_ManagePO.set_CSSSELECTOR_row_1tdnth_child1_1(), is("Project001"));
        assertThat(_ManagePO.set_CSSSELECTOR_row_1tdnth_child2(), is("release"));
        assertThat(_ManagePO.set_CSSSELECTOR_row_1tdnth_child4(), is("public"));
        assertThat(_ManagePO.set_CSSSELECTOR_row_1tdnth_child5(), is("Description"));
        _ManageProjectsPO.doLogout();
    }

    @Test
    public void test5AddAlreadyExistingProject() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_NAME_username("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToManage();
        ManagePO _ManagePO = new ManagePO(driver, js, vars);
        _ManagePO.goToManageProjects();
        ManageProjectsPO _ManageProjectsPO = new ManageProjectsPO(driver, js, vars);
        _ManageProjectsPO.goToCreateProject();
        CreateProjectPO _CreateProjectPO = new CreateProjectPO(driver, js, vars);
        _CreateProjectPO.createProject("Project001", "release", "Description");
        _ManageProjectsPO.goToManage_1();
        assertThat(_ManageProjectsPO.set_CSSSELECTOR_trnth_child2td_1(), is("A project with that name already exists. Please go back and enter a different name."));

        WebElement element = driver.findElement(By.xpath("//p"));
        String attribute = element.getAttribute("style");
        vars.put("_style", attribute);

        assertEquals(vars.get("_style").toString(), "color: red;");
        _ManageProjectsPO.doLogout();
    }

    @Test
    public void test6AddCategory() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_NAME_username("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToManage();
        ManagePO _ManagePO = new ManagePO(driver, js, vars);
        _ManagePO.goToManageProjects();
        ManageProjectsPO _ManageProjectsPO = new ManageProjectsPO(driver, js, vars);
        _ManageProjectsPO.goToEdit001();
        Edit001PO _Edit001PO = new Edit001PO(driver, js, vars);
        _Edit001PO.addCategory("Category001", true, true, null, false, false);
        assertThat(_Edit001PO.set_CSSSELECTOR_tbodynth_child1row_1nth_child3tdnth_child1_1(), is("Category001"));
        _Edit001PO.doLogout();
    }

    @Test
    public void test7AddAlreadyExistingCategory() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_NAME_username("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToManage();
        ManagePO _ManagePO = new ManagePO(driver, js, vars);
        _ManagePO.goToManageProjects();
        ManageProjectsPO _ManageProjectsPO = new ManageProjectsPO(driver, js, vars);
        _ManageProjectsPO.goToEdit001();
        Edit001PO _Edit001PO = new Edit001PO(driver, js, vars);
        _Edit001PO.addCategory(null, false, false, "Category001", true, true);
        assertThat(_Edit001PO.set_CSSSELECTOR_trnth_child2center_1(), is("A category with that name already exists."));
        
        WebElement element = driver.findElement(By.xpath("//p"));
        String attribute = element.getAttribute("style");
        vars.put("_style", attribute);
        
        assertEquals(vars.get("_style").toString(), "color: red;");
        _Edit001PO.doLogout();
    }

    @Test
    public void test8AddIssue() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_NAME_username_1("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToReportIssue();
        ReportIssuePO _ReportIssuePO = new ReportIssuePO(driver, js, vars);
        _ReportIssuePO.reportIssue("Category001", "random", "crash", "immediate", "Summary001", "description001");
        ViewAllBugPO _ViewAllBugPO = new ViewAllBugPO(driver, js, vars);
        _ViewAllBugPO.goToViewIssues();
        assertThat(_ViewAllBugPO.set_CSSSELECTOR_centernth_child6_1(), is("Category001"));
        assertThat(_ViewAllBugPO.set_CSSSELECTOR_centernth_child7(), is("crash"));
        assertThat(_ViewAllBugPO.set_CSSSELECTOR_leftnth_child10(), is("Summary001"));
        _ViewAllBugPO.doLogout();
    }

    @Test
    public void test9AssignIssueToAdmin() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_NAME_username("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToViewIssues();
        ViewAllBugPO _ViewAllBugPO = new ViewAllBugPO(driver, js, vars);
        _ViewAllBugPO.assignIssueToAdmin("Assign");
        assertThat(_ViewAllBugPO.set_CSSSELECTOR_centernth_child8_1(), is("assigned (administrator)"));
        _ViewAllBugPO.doLogout();
    }

    @Test
    public void test10ChangeIssuePriority() {
        driver.get("http://localhost:3000/mantisbt/login_page.php");
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_NAME_username("administrator", "root");
        MyViewPO _MyViewPO = new MyViewPO(driver, js, vars);
        _MyViewPO.goToViewIssues();
        ViewAllBugPO _ViewAllBugPO = new ViewAllBugPO(driver, js, vars);
        _ViewAllBugPO.goToEditIssue();
        EditIssuePO _EditIssuePO = new EditIssuePO(driver, js, vars);
        _EditIssuePO.changeIssuePriority("low");
        assertThat(_EditIssuePO.set_CSSSELECTOR_width100nth_child8row_2nth_child7tdnth_child2_1(), is("low"));
        ViewIssuePO _ViewIssuePO = new ViewIssuePO(driver, js, vars);
        _ViewIssuePO.doLogout();
    }
}